name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Build & Test
        run: |
          mvn -f StudentGrams/pom.xml clean package
          mvn -f StudentGrams/pom.xml test

      - name: Run Lint Checks
        run: |
          mvn -f StudentGrams/pom.xml checkstyle:check
          mvn -f StudentGrams/pom.xml pmd:check

      - name: SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=StudentGrams
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
