name: Sonar Scan

on:
  push:
    branches:
      - "*"

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List files (for debug)
        run: ls -R

      - name: Run SonarQube Scan
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -DskipTests
        working-directory: StudentGrams
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io/
