name: Super-Linter

on:
  pull_request:
    branches:
      - develop
      - main
      - "*"
  push:
    branches:
      - develop
      - main
      - "*"

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_GITHUB_ACTIONS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}